services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage for database
    ports:
      - "5433:5432"
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    volumes:
      - .:/app
    ports:
      - "8887:8887"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
