services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage for database
    ports:
      - "5433:5432"
    env_file:
      - .env

  app:
    build: .
    command: bash -c "./jupyter/start_jupyter.sh && tail -f /app/log/jupyter.log"
    volumes:
      - .:/app
    ports:
      - "8887:8887"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: