# Dockerfile for PostgreSQL with PostGIS
FROM postgres:15

# Install PostGIS
RUN apt-get update && \
    apt-get install -y postgis postgresql-15-postgis-3 gdal-bin && \
    rm -rf /var/lib/apt/lists/*

# Copy the initialization script to the Docker container
COPY docker/init_postgis.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init_postgis.sh



