name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the app Docker image
      env:
        DB_HOST: test
        DB_USER: test
        DB_PASSWORD: test
      run: docker build . --file Dockerfile --tag climb_wise-app:$(date +%s)
