name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the app Docker image
      run: docker build . --file docker/Dockerfile.app --tag climb_wise-app:$(date +%s)
    - name: Build the db Docker image
      run: docker build . --file docker/Dockerfile.db --tag climb_wise-db:$(date +%s)
